trigger:
- main  # rama que dispara el pipeline

stages:
- stage: DeployToVM
  jobs:
  - deployment: InstallApacheAndDeploy
    displayName: "Instalar Apache y desplegar app estática"

    environment:
      name: "VM-DEVOPS-LINUX"   # Nombre de entorno en DevOps
      resourceType: VirtualMachine

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self   # Clonar repo en el agente de pipeline

          - script: |
              echo "Iniciando instalación de Apache...se omite si existe apache"
              sudo apt-get update
              sudo apt-get install -y apache2
              
              echo "Copiando archivos del repo a /var/www/html"
              sudo rm -rf /var/www/html/*
              sudo cp -r $(System.DefaultWorkingDirectory)/* /var/www/html/

              sudo systemctl restart apache2
              echo "Despliegue completado. Sitio disponible en Apache."
            displayName: "Instalar Apache y desplegar aplicación"
